### ISSUE TITLE
[ui] 평가 페이지 뷰 구현

### ISSUE THREAD

**Issue by hyo-limilimee** [SSU-OpenSource/Front-AOS#12]
## ISSUE
- 평가페이지 뷰 작업

## To-do
- [x] 초기 평가 페이지(과목 페이지) 뷰 작업
- [x] 리싸이클러뷰 사용하여 목록 띄우기
- [x] 과목별 팀원 평가 페이지 뷰 작업

## 참고사항 및 체크포인트
평가 지표와 시크바 구현에 대한 논의 필요 -> 해결
