### ISSUE TITLE
[ui] 팀원 프로필 열람 페이지 뷰 구현

### ISSUE THREAD

**Issue by hyo-limilimee** [SSU-OpenSource/Front-AOS#22]
## ISSUE
- 팀원 프로필 열람 페이지 뷰 구현

## To-do
- [x] 팀장 입장에서 신청 열람 페이지 구현 
- [x] 팀장 입장 신청 수락 페이지 구현
- [x] 프로필 열람을 클릭했을 때 뜨는 페이지 구현

## 참고사항 및 체크포인트
과목 삭제에 관한 뷰 피그마에 존재하지 않음. -> 어떻게 구현할지 회의 필요 -> 해결
