### ISSUE TITLE
[feat] 약관화면 기능 구현

### ISSUE THREAD

**Issue by yeriinnn** [SSU-OpenSource/Front-AOS#35]
## ISSUE
- 약관화면 기능 구현

## To-do
- [ ] 서비스이용약관 이동 및 전 화면으로 돌아가는 기능 구현
- [ ] 개인정보처리방침 이동 및 전 화면으로 돌아가는 기능 구현
- [ ] 서비스 이용약관 및 개인정보처리방침 작성 후 백 전달(위키)
