### ISSUE TITLE
[feat] 평가 페이지 seek bar 구현

### ISSUE THREAD

**Issue by hyo-limilimee** [SSU-OpenSource/Front-AOS#43]
## ISSUE
- 평가 페이지 seek bar 구현

## To-do
- [x] 시크바 색상 조정
- [x] 시크바 눈금 조정
- [x] 10단위로 끊기게 조정
