### ISSUE TITLE
[fix] 마이페이지 변경 부분 기능 구현

### ISSUE THREAD

**Issue by hyo-limilimee** [SSU-OpenSource/Front-AOS#50]
## ISSUE
- 마이페이지 변경 부분 기능 구현

## To-do
- [x] 비밀번호 변경 시 액티비티 전환
- [x] 닉네임 변경 시 액티비티 전환
- [X] 화살표 클릭시 뒤로가기 구현
