### ISSUE TITLE
[feat] 팀 빌딩 페이지 다이얼로그 / 스피너 구현

### ISSUE THREAD

**Issue by hyo-limilimee** [SSU-OpenSource/Front-AOS#60]
## ISSUE
- 팀 빌딩 페이지 다이얼로그 / 스피너 구현

## To-do
- [x] 작성 완료 클릭 시 다이얼로그 구현
- [X]  날짜 선택 다이얼로그 구현
- [X] 모집 인원 선택 스피너 구현
