### ISSUE TITLE
[feat] 로그인 api 붙이기 및 세부 기능 구현

### ISSUE THREAD

**Issue by yeriinnn** [SSU-OpenSource/Front-AOS#72]
## ISSUE
- 로그인 api 붙이기 및 세부 기능 구현

## To-do
- [x] 로그인 api 붙이기
- [x] 바텀네비 관련 수정
- [x] 회원가입api 붙이기
- [x] 바텀네비 애니메이션 제거
